ERROR [2015-05-09 23:16:46,680] main                 Engine.main: error connecting to the database atavism.server.util.AORuntimeException: could not connect to database: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
       at atavism.server.engine.Database.connect(Database.java:126)
       at atavism.server.engine.Engine.main(Engine.java:356)
ERROR [2015-05-09 23:16:47,016] main                 Engine.main: error connecting to the database atavism.server.util.AORuntimeException: could not connect to database: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
       at atavism.server.engine.Database.connect(Database.java:126)
       at atavism.server.engine.Engine.main(Engine.java:356)
ERROR [2015-05-09 23:16:47,090] main                 Engine.main: error connecting to the database atavism.server.util.AORuntimeException: could not connect to database: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
       at atavism.server.engine.Database.connect(Database.java:126)
       at atavism.server.engine.Engine.main(Engine.java:356)
ERROR [2015-05-09 23:16:47,210] main                 Engine.main: error connecting to the database atavism.server.util.AORuntimeException: could not connect to database: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
       at atavism.server.engine.Database.connect(Database.java:126)
       at atavism.server.engine.Engine.main(Engine.java:356)
ERROR [2015-05-09 23:16:47,565] main                 Engine.main: error connecting to the database atavism.server.util.AORuntimeException: could not connect to database: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
       at atavism.server.engine.Database.connect(Database.java:126)
       at atavism.server.engine.Engine.main(Engine.java:356)
ERROR [2015-05-09 23:16:47,628] main                 Engine.main: error connecting to the database atavism.server.util.AORuntimeException: could not connect to database: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
       at atavism.server.engine.Database.connect(Database.java:126)
       at atavism.server.engine.Engine.main(Engine.java:356)
ERROR [2015-05-09 23:16:47,761] main                 Engine.main: error connecting to the database atavism.server.util.AORuntimeException: could not connect to database: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
       at atavism.server.engine.Database.connect(Database.java:126)
       at atavism.server.engine.Engine.main(Engine.java:356)
ERROR [2015-05-09 23:16:48,210] main                 Engine.main: error connecting to the database atavism.server.util.AORuntimeException: could not connect to database: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
       at atavism.server.engine.Database.connect(Database.java:126)
       at atavism.server.engine.Engine.main(Engine.java:356)
ERROR [2015-05-09 23:16:48,369] main                 Engine.main: error connecting to the database atavism.server.util.AORuntimeException: could not connect to database: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
       at atavism.server.engine.Database.connect(Database.java:126)
       at atavism.server.engine.Engine.main(Engine.java:356)
ERROR [2015-05-09 23:17:05,371] main                 Engine.main: error connecting to the database atavism.server.util.AORuntimeException: could not connect to database: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
       at atavism.server.engine.Database.connect(Database.java:126)
       at atavism.server.engine.Engine.main(Engine.java:356)
ERROR [2015-05-09 23:17:05,458] main                 Engine.main: error connecting to the database atavism.server.util.AORuntimeException: could not connect to database: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
       at atavism.server.engine.Database.connect(Database.java:126)
       at atavism.server.engine.Engine.main(Engine.java:356)
ERROR [2015-05-09 23:17:05,648] main                 Engine.main: error connecting to the database atavism.server.util.AORuntimeException: could not connect to database: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
       at atavism.server.engine.Database.connect(Database.java:126)
       at atavism.server.engine.Engine.main(Engine.java:356)
ERROR [2015-05-09 23:17:05,937] main                 Engine.main: error connecting to the database atavism.server.util.AORuntimeException: could not connect to database: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
       at atavism.server.engine.Database.connect(Database.java:126)
       at atavism.server.engine.Engine.main(Engine.java:356)
ERROR [2015-05-09 23:17:06,409] main                 Engine.main: error connecting to the database atavism.server.util.AORuntimeException: could not connect to database: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
       at atavism.server.engine.Database.connect(Database.java:126)
       at atavism.server.engine.Engine.main(Engine.java:356)
ERROR [2015-05-09 23:17:06,861] main                 Engine.main: error connecting to the database atavism.server.util.AORuntimeException: could not connect to database: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
       at atavism.server.engine.Database.connect(Database.java:126)
       at atavism.server.engine.Engine.main(Engine.java:356)
ERROR [2015-05-09 23:17:07,041] main                 Engine.main: error connecting to the database atavism.server.util.AORuntimeException: could not connect to database: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
       at atavism.server.engine.Database.connect(Database.java:126)
       at atavism.server.engine.Engine.main(Engine.java:356)
ERROR [2015-05-09 23:17:07,276] main                 Engine.main: error connecting to the database atavism.server.util.AORuntimeException: could not connect to database: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
       at atavism.server.engine.Database.connect(Database.java:126)
       at atavism.server.engine.Engine.main(Engine.java:356)
ERROR [2015-05-09 23:17:07,380] main                 Engine.main: error connecting to the database atavism.server.util.AORuntimeException: could not connect to database: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
       at atavism.server.engine.Database.connect(Database.java:126)
       at atavism.server.engine.Engine.main(Engine.java:356)
